version: 2.1

jobs:
  install:
    docker:
      - image: cimg/base:stable
    steps:
      - run: yarn install

  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run: yarn build

workflows:
  Quality:
    jobs:
      - install
      - build:
          requires:
            - install
